# Generated by Django 5.2.7 on 2025-12-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_producto_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
    ]
