# Generated by Django 5.2.8 on 2025-11-27 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
